export const CART_ADAUGA_ITEM = "CART_ADAUGA_ITEM";
export const CART_ELIMINA_ITEM = "CART_ELIMINA_ITEM";
export const CART_SAVE_SHIPPING_ADDRESS = "CART_SAVE_SHIPPING_ADDRESS";
export const CART_SAVE_PAYMENT_METHOD = "CART_SAVE_PAYMENT_METHOD";
export const CART_CLEAR_ITEMS = "CART_CLEAR_ITEMS";
